# general settings
name: train_SRFormer_X4_b4_w16
model_type: SwinIRModel
scale: 4
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: MRI_Train
    type: PairedImageDataset
    dataroot_gt: datasets/MRI/GT/Train
    dataroot_lq: datasets/MRI/TrainLR/AREA
    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 256
    use_hflip: true
    use_rot: true

    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~


  val_1:
    name: AREA
    type: PairedImageDataset
    dataroot_gt: datasets/MRI/GT/Validation
    dataroot_lq: datasets/MRI/ValLR/AREA
    io_backend:
      type: disk

  val_2:
    name: NN
    type: PairedImageDataset
    dataroot_gt: datasets/MRI/GT/Validation
    dataroot_lq: datasets/MRI/ValLR/NEAREST
    io_backend:
      type: disk

  val_3:
    name: TRAIN
    type: PairedImageDataset
    dataroot_gt: datasets/MRI/GT/Train
    dataroot_lq: datasets/MRI/TrainLR/AREA
    io_backend:
      type: disk

# network structures
network_g:
  type: SRFormer
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
print_network: false
# pretrain path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [5000, 10000, 15000, 20000, 25000, 30000]
    gamma: 0.5

  total_iter: 35000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 28500
